__include__: [
  '../ecdet/ecdet_s.yml',
  'ecseg.yml',
  '../dataset/fangxuanping.yml',
]

output_dir: outputs/ecseg_s_fangxuanping

ViTAdapter:
  name: ecseg_vitt
  weights_path: ecvits/ecseg_vitt.pth

use_amp: true

eval_spatial_size: [640, 640] # h w

train_dataloader:
  total_batch_size: 2      # 全局 Batch Size（需根据显存容量调整）
  dataset:
    transforms:
      mosaic_epoch: 36        # Mosaic 增强截止轮次
      mosaic_prob: 0.75       # Mosaic 增强触发概率
      stop_epoch: 72          # 增强停止轮次

  collate_fn:
    mixup_prob: 0.75          # MixUp 增强概率
    mixup_epoch: 36           # MixUp 增强截止轮次
